### ISSUE TITLE
关于域名端口转发的问题

### ISSUE THREAD

**Issue by cj1357** [zangxx66/nonebot_plugin_blive_danmaku#10]
如果自定义端口转发，不用默认的80端口，改用8001，可以成功打开面板，但是所有的封面都获取不到。
我查了一下好像请求封面的url没有指定端口号，这个要怎么设置呢？
![image](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/40661342/02d3ae27-65ff-4a79-8945-aa9921dde00a)

**Comment by cj1357** [comment]
明白了，更改了转发域名的端口之后，之前的图片读的url还是原先配置的域名跟默认端口号80，新开播之后的数据现在已经正确去读8001端口了，那之前的是因为缓存？（不过之后没问题了就好）
![image](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/40661342/18052070-4594-4a7a-b7cf-9538281c2472)

**Comment by zangxx66** [comment]
ok，下个版本加一个清除图片缓存
