### ISSUE TITLE
功能建议：希望添加一个下播提醒

### ISSUE THREAD

**Issue by Oranges4001** [zangxx66/nonebot_plugin_blive_danmaku#13]

**Comment by zangxx66** [comment]
下播提醒是有的  
![QQ截图20230704091708](https://github.com/zangxx66/nonebot_plugin_blive_danmaku/assets/14540861/28d39b5c-e2f9-4902-acf2-a4c3e72ace32)

**Comment by Oranges4001** [comment]
好的
