### ISSUE TITLE
错误码401如何解决

### ISSUE THREAD

**Issue by nanlu404** [zangxx66/nonebot_plugin_blive_danmaku#15]
错误码401如何解决

**Comment by zangxx66** [comment]
你好 @nanlu404，我已收到你的issue，问题有新的进展或疑问我会及时回复你。

**Comment by nanlu404** [comment]
在添加订阅的时候发生未知错误：错误码: -401, 信息: 非法访问，请联系开发者

**Comment by zangxx66** [comment]
更新插件  `nb plugin update nonebot-plugin-blive-danmaku`
