### ISSUE TITLE
能不能加个开播提醒？检测到开播自动推送群消息

### ISSUE THREAD

**Issue by liuzj288** [zangxx66/nonebot_plugin_blive_danmaku#3]

**Comment by zangxx66** [comment]
开播提醒有[HarukaBot](https://github.com/SK-415/HarukaBot)和[bilibilibot](https://github.com/TDK1969/nonebot_plugin_bilibilibot)了，如果和其他插件的功能重复了可能会对使用的人造成困扰

**Comment by liuzj288** [comment]
> 开播提醒有[HarukaBot](https://github.com/SK-415/HarukaBot)和[bilibilibot](https://github.com/TDK1969/nonebot_plugin_bilibilibot)了，如果和其他插件的功能重复了可能会对使用的人造成困扰
config加个开关就行。主要是不想装很多插件

**Comment by zangxx66** [comment]
v0.1.4已更新

**Comment by zangxx66** [comment]
#5
