### ISSUE TITLE
会适配到py3.9吗？

### ISSUE THREAD

**Issue by Nenot233** [zangxx66/nonebot_plugin_blive_danmaku#4]

**Comment by zangxx66** [comment]
nonebot2的商店审核需要py3.10

**Comment by Nenot233** [comment]
我是py3.9，请问可以用吗

**Comment by Nenot233** [comment]
似乎不行，希望可以适配py3.9

**Comment by zangxx66** [comment]
请尝试以下操作
1. clone本仓库
```
git clone https://github.com/zangxx66/nonebot_plugin_blive_danmaku
```
2. 切换到仓库目录
```
cd nonebot_plugin_blive_danmaku
```
3. 将仓库目录下的nonebot_plugin_blive_danmaku文件夹复制到你的bot目录下的`.venv/Lib/site-packages`内，或者python的site-packages内，例如
```
cp -r nonebot_plugin_blive_danmaku/ <your_bot_path>/.venv/Lib/site-packages/
```  
4. 编辑`pyproject.toml`文件，在`plugins`新增`nonebot_plugin_blive_danmaku`
```
plugins=["nonebot_plugin_blive_danmaku"]
```

**Comment by zangxx66** [comment]
请问是否有遇到问题，没有的话先关闭了

**Comment by Nenot233** [comment]
有点没整明白）

**Comment by zangxx66** [comment]
> 有点没整明白）

请尝试本地安装这个版本  
https://github.com/zangxx66/nonebot_plugin_blive_danmaku/releases/tag/py3.8-py3.9
