### ISSUE TITLE
打印的日志“爬取路灯列表”好频繁，一下子屏幕就被占满了

### ISSUE THREAD

**Issue by cj1357** [zangxx66/nonebot_plugin_blive_danmaku#5]
![image](https://user-images.githubusercontent.com/40661342/230839388-4915bff2-cc8d-4a32-98cb-ed7bf8cc04fe.png)
这个日志一般我们也不关注吧，满屏都是这个有时候看其它插件的日志有点不方便了

**Comment by zangxx66** [comment]
v0.1.4已更新

**Comment by zangxx66** [comment]
如果没有其他反馈就先关闭了
