### ISSUE TITLE
tortoise.exceptions.ConfigurationError: default_connection for the model <class 'nonebot_plugin_blive_danmaku.database.model.Sub'> cannot be None

### ISSUE THREAD

**Issue by cj1357** [zangxx66/nonebot_plugin_blive_danmaku#6]
更新到版本0.1.4启动bot有报错，用0.1.3版本的正常
系统debian11
.env.dev里面配置danmaku_group_notice = True
![image](https://user-images.githubusercontent.com/40661342/231041021-6d1695a3-5c97-4e94-84a1-a8dc0d7d7088.png)

**Comment by cj1357** [comment]
> 更新到版本0.1.4启动bot有报错，用0.1.3版本的正常 系统debian11 .env.dev里面配置danmaku_group_notice = True ![image](https://user-images.githubusercontent.com/40661342/231041021-6d1695a3-5c97-4e94-84a1-a8dc0d7d7088.png)

![image](https://user-images.githubusercontent.com/40661342/231041916-b6be72eb-b3c0-49ac-a48e-5f57cd6d2e28.png)
这个是上面报错后再接下来的报错，导致bot停止运行了，不知道是不是上面的报错导致的

**Comment by zangxx66** [comment]
已更新，pip或者nb-cli更新一下插件

**Comment by cj1357** [comment]
但是这个版本号好像还是0.1.4？难道本地没有推上来么🙁

**Comment by zangxx66** [comment]
> 但是这个版本号好像还是0.1.4？难道本地没有推上来么🙁

从pypi获取

**Comment by cj1357** [comment]
更新了但是还会报这个错：tortoise.exceptions.ConfigurationError: default_connection for the model <class 'nonebot_plugin_blive_danmaku.database.model.Sub'> cannot be None 但是这次没有导致bot进程结束了，只是插件报错
我还是先用0.1.3版本的好了
![image](https://user-images.githubusercontent.com/40661342/231163471-e585992a-91c4-48d5-aa8d-ab2218270c3a.png)
![image](https://user-images.githubusercontent.com/40661342/231162943-003263f7-541f-4563-9046-4aff7f34d487.png)
![image](https://user-images.githubusercontent.com/40661342/231163331-c18c2d33-e3a6-4d0e-8d12-b01c932b3c23.png)

**Comment by zangxx66** [comment]
> 更新了但是还会报这个错：tortoise.exceptions.ConfigurationError: default_connection for the model <class 'nonebot_plugin_blive_danmaku.database.model.Sub'> cannot be None 但是这次没有导致bot进程结束了，只是插件报错 我还是先用0.1.3版本的好了 ![image](https://user-images.githubusercontent.com/40661342/231163471-e585992a-91c4-48d5-aa8d-ab2218270c3a.png) ![image](https://user-images.githubusercontent.com/40661342/231162943-003263f7-541f-4563-9046-4aff7f34d487.png) ![image](https://user-images.githubusercontent.com/40661342/231163331-c18c2d33-e3a6-4d0e-8d12-b01c932b3c23.png)

把你的bot根目录/data/danmakuBot.sqlite3的这个文件删了，重新运行看看

**Comment by cj1357** [comment]
把这3个文件都删掉了，重启还是报同样的错，然后data文件夹里面又重新生成了那3个文件，再次重启还是报错
再次重新安装0.1.3版本的，删掉那3个文件重启没有报错，正常运行（有这个路灯的功能已经超棒了🤗，再不济的话我可以一直用0.1.3版本😁）
![6CY{XY}G3QE5J79WZZS7I)U](https://user-images.githubusercontent.com/40661342/231190454-471fc6f4-1e32-4ce3-b893-96d8e3122f7c.png)

**Comment by zangxx66** [comment]
> 把这3个文件都删掉了，重启还是报同样的错，然后data文件夹里面又重新生成了那3个文件，再次重启还是报错 再次重新安装0.1.3版本的，删掉那3个文件重启没有报错，正常运行（有这个路灯的功能已经超棒了🤗，再不济的话我可以一直用0.1.3版本😁） ![6CY{XY}G3QE5J79WZZS7I)U](https://user-images.githubusercontent.com/40661342/231190454-471fc6f4-1e32-4ce3-b893-96d8e3122f7c.png)

更新一下插件，应该是可以了

**Comment by cj1357** [comment]
更新了，这次加载插件没有报错了，但是使用命令"查看订阅"的时候会报list的错
![image](https://user-images.githubusercontent.com/40661342/231333319-1e7b78a7-f063-4b5a-85c5-694ac2a8e53a.png)

**Comment by cj1357** [comment]
> 更新了，这次加载插件没有报错了，但是使用命令"查看订阅"的时候会报list的错 ![image](https://user-images.githubusercontent.com/40661342/231333319-1e7b78a7-f063-4b5a-85c5-694ac2a8e53a.png)

添加订阅、删除订阅、开启路灯都是正常的，就这个查看订阅会报错，如果没有订阅，使用查看订阅不会报错

**Comment by zangxx66** [comment]
> > 更新了，这次加载插件没有报错了，但是使用命令"查看订阅"的时候会报list的错 ![image](https://user-images.githubusercontent.com/40661342/231333319-1e7b78a7-f063-4b5a-85c5-694ac2a8e53a.png)
> 
> 添加订阅、删除订阅、开启路灯都是正常的，就这个查看订阅会报错，如果没有订阅，使用查看订阅不会报错

更新一下插件再试试看

**Comment by cj1357** [comment]
版本是0.1.64，可以了，谢谢😺
![image](https://user-images.githubusercontent.com/40661342/231340187-1b90e6e4-198a-4256-8d5d-013740ead454.png)
默认开播提醒是打开的么，喔，那是我在env配置了true
![image](https://user-images.githubusercontent.com/40661342/231339124-e9c82687-9674-44ca-b23d-7b26958a38f5.png)

**Comment by zangxx66** [comment]
> 

默认是关，在env配置了以env的为准

**Comment by cj1357** [comment]
> > 
> 
> 默认是关，在env配置了以env的为准

明白了😺
