### ISSUE TITLE
查询面板的网址打不开

### ISSUE THREAD

**Issue by cj1357** [zangxx66/nonebot_plugin_blive_danmaku#9]
是外网服务器，我配置了danmuku_host为对应的服务器公网ip地址了（换成域名也是打不开），但是打开链接访问不了那个面板，这个我要怎么配置呢，我发现直接访问http://ip也是访问不了的，也是提示“当前无法处理此请求”，直接ping是可以ping通的
![image](https://user-images.githubusercontent.com/40661342/232320823-bbb5dc69-6f2d-4d15-a366-3d9422f27d4e.png)
![image](https://user-images.githubusercontent.com/40661342/232320833-d9102f20-d07c-4349-89e9-482afbcd6cf4.png)

**Comment by zangxx66** [comment]
1.检查服务器的端口是否开放  
2.服务器需要配置一个反向代理服务器转发网页请求到机器人的端口上，如果port没有更改的话就是转发到本地`http://127.0.0.1:8080/`上

**Comment by cj1357** [comment]
> 1.检查服务器的端口是否开放 2.服务器需要配置一个反向代理服务器转发网页请求到机器人的端口上，如果port没有更改的话就是转发到本地`http://127.0.0.1:8080/`上

我看了一下机器人的端口就是8080，然后我查找了一下怎么配置：

**Comment by cj1357** [comment]
> 1.检查服务器的端口是否开放 2.服务器需要配置一个反向代理服务器转发网页请求到机器人的端口上，如果port没有更改的话就是转发到本地`http://127.0.0.1:8080/`上

我看了一下机器人的端口确实是8080，然后我查询了一下怎么配置转发：

如果您使用的是 Debian 系统并且已经安装了 Apache，您可以通过以下步骤将网页请求转发到本地的 http://127.0.0.1:8080/：
1. 在 `/etc/apache2/sites-available` 目录下创建一个虚拟主机配置文件，例如 `my-site.conf`。
2. 在该文件中，您可以使用以下配置来将请求转发到本地的 http://127.0.0.1:8080/：
```
<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
```
3. 保存并关闭文件。
4. 运行 `sudo a2ensite my-site` 命令来启用您刚才创建的虚拟主机。
5. 运行 `sudo systemctl restart apache2` 命令来重启 Apache 以使更改生效。
按照上面的方法执行了之后还是打不开面板，但是网页变成了404 not found，不是之前的“当前无法使用此页面”了，我的步骤哪个地方有问题么
![image](https://user-images.githubusercontent.com/40661342/232320866-761601a2-df44-483a-a74a-5b21fe10606d.png)

**Comment by cj1357** [comment]
是那个回答有问题，我去网上找了一下反向代理的正确格式，改成下面这样就好了：

**Comment by cj1357** [comment]
是那个回答有问题，我去网上找了一下反向代理的正确格式，改成下面这样就好了：
```
<VirtualHost *:80>
    ServerName XX.XX.36.199 #也可以换成域名
    ProxyRequests off
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
</VirtualHost>
```
可以了，这个管理面板真方便，感谢大大😆

**Comment by zangxx66** [comment]
问题解决了就好，下次记得把服务器地址打个码:stuck_out_tongue_closed_eyes:
